### ISSUE TITLE
auro-flightline: update stop size on mobile

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-flightline#11]
## Is your feature request related to a problem? Please describe.
Per @KyleJones2 and @designingcircles, the size of the circle for each stop should be 12px on a mobile screen size. It is currently 16px.

## Describe the solution you'd like
Update the width and height of the circle.

## Describe alternatives you've considered
n/a

**Comment by blackfalcon** [comment]
I really want to consult with @gusnaughton and @erikalanghauser on this one. I am not sure what is the source of truth here? 

The issues we seem to be running into are decisions being made during development that are not retroactively updated in the design docs.

When there are these types of disputes I am recommending that the person who discovers the issue communicates with the past authors of the design and code to resolve what is Truth.

**Comment by erikalanghauser** [comment]
@blackfalcon - I just synced with @KyleJones2 and @designingcircles. We are aligned on these changes to auro-flightline in the mobile breakpoint. Thank you!

**Comment by blackfalcon** [comment]
Ok, I will get this addressed ASAP, it's a pretty small change.
