### ISSUE TITLE
v2.0-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-flightline#24]
## NEXT MAJOR release 

The following items are to be included with the next release of the `auro-flighline`, all PRs are to be from the feature branch to `v2.0-rc` branch.

- [ ] https://github.com/AlaskaAirlines/auro-flightline/issues/15
- [ ] https://github.com/AlaskaAirlines/auro-flightline/issues/4
- [ ] #25

**Comment by braven112** [comment]
closing in favor of issues and milestones
