### ISSUE TITLE
v1.2-rc

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-flightline#26]
# Release Candidate

All these issues will be considered for the next release of auro-flightline.  

## Merged

- https://github.com/AlaskaAirlines/auro-flightline/issues/17
- https://github.com/AlaskaAirlines/auro-flightline/issues/21
- https://github.com/AlaskaAirlines/auro-flightline/issues/15

**Comment by blackfalcon** [comment]
@braven112 we should have a formal kickoff with @geoffrich and team to make sure that are all on the same page regarding scope and expectations of this work since they are willing to take on the work.

**Comment by blackfalcon** [comment]
@braven112 I'd suggest we release with what we have. The issues that have been closed have been in wait for a long time and we are warning for @geoffrich to complete #25 

So, I'd recommend that we move that to the next RC.

**Comment by braven112** [comment]
I agree
