### ISSUE TITLE
Container query is not working as expected in Auro doc site

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro-flightline#29]
## To Reproduce
1. Go to https://auro.alaskaair.com/components/auro/flightline#:~:text=See%20code-,Container%20query,-The%20auro%2Dflightline
1. Resize the window to trigger container query
1. See error

## Expected behavior

Flightline UI should trigger at parent container size, not media size. 

## Screenshots

**Expected:**
<img width="500" alt="Screen Shot 2022-01-07 at 8 37 56 AM" src="https://user-images.githubusercontent.com/181089/148576193-831b5b08-f8af-4e9f-941f-c273a1f93c02.png">

**Current:** 
<img width="506" alt="Screen Shot 2022-01-07 at 8 38 05 AM" src="https://user-images.githubusercontent.com/181089/148576212-7cfb4c74-f369-4072-b7c6-dbfc691b770e.png">

## Desktop/Smartphone (please complete the following information):
 - OS: [macOS and iOS]
 - Device: [iPhone 12]
 - Browser [chrome, safari]
 - Version [current]

## Additional context

The issue appears to be related to the Auro doc site in some way. Running a local demo does not repro this error.

**Comment by geoffrich** [comment]
This is because the doc site also loads a bundled version of auro-flight, which includes the old version of auro-flightline. Since the auro-flight version of auro-flightline is defined first, it wins out over the more recent version.

Possible mitigation is to load flightline before flight, but this is an inherent risk of using bundled versions of custom elements (only one version can be defined at a time).

**Comment by blackfalcon** [comment]
Issue addressed with auro-flight commit https://github.com/AlaskaAirlines/auro-flight/commit/3d66bffc8a84e68f2978800a71bcd2a993404bf2

New issue created https://github.com/AlaskaAirlines/auro-flight/issues/22 to remove the nested dependency.

**Comment by blackfalcon** [comment]
Screen shot from Auro doc site post release. 

<img width="1106" alt="Screen Shot 2022-01-09 at 5 12 11 PM" src="https://user-images.githubusercontent.com/181089/148708769-891fff09-a46b-409c-9da8-c6832a36899d.png">
