### ISSUE TITLE
auro-flightline: z-index overlaps header

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-flightline#7]
## Describe the bug
![image](https://user-images.githubusercontent.com/7005799/118340128-b605de80-b4cf-11eb-85cb-a7eeb131c688.png)

## To Reproduce
The new schedules view (alaskaair.com/status/628/2021-05-14) and scroll up on a mobile viewport

## Expected behavior
auro-flight-segment doesn't overlap the headerfooter

**Comment by blackfalcon** [comment]
Here is what I know. The `z-index` for the dot is `2`. The `z-index` for the header is `499`. 

Is there a better production URL I can see to repro this?

**Comment by geoffrich** [comment]
Minimal repro: https://codepen.io/geoff-rich/pen/LYWRLVY

**Comment by blackfalcon** [comment]
@gusnaughton the URL you have to demo the issue no longer has a stopover to illustrate the actual bug you are reporting.

**Comment by blackfalcon** [comment]
@gusnaughton Do you have an updated example where we can repro this issue?

**Comment by blackfalcon** [comment]
Added BLOCKED label. Unable to repro. @gusnaughton is you have an example we can use to repro, we can see if there is a solution or I will have to close the issue.

**Comment by geoffrich** [comment]
@blackfalcon we ran into similar z-index issues in disruptions. We had to work around it by setting z-index on the flightline and our overlay and it was a bit of a pain.

As an example, the "canceled" flightline was appearing over our flight details overlay (note the dashed red line under the heading):
![Screen Shot 2021-06-16 at 14 41 08](https://user-images.githubusercontent.com/4992896/122298013-157d5280-ceb1-11eb-83bb-742940bbc26d.png)

You can repro similar behavior in the flightline demo repo by adding a fixed heading to the top of the demo page:
```html
<style>
  .h-cont {
    position: relative;
    z-index: 1;
  }

  .heading {
    background: lightblue;
    position: fixed;
    top: 0;
    right: 0;
    left: 0;
    height: 100px;
  }
</style>
<div class="h-cont">
  <div class="heading">
    I'm a heading
  </div>
</div>
```

Here's a gif of the result:
![z-index](https://user-images.githubusercontent.com/4992896/122298320-74db6280-ceb1-11eb-9d30-ed51f62b278f.gif)

It is not difficult to get into this situation and is a significant pain point for those using the component. By using z-index in this way, we break the isolation that a component model promises. 

I think this issue should be reopened. I've been messing around in the repo and I think we can resolve this by removing some of the z-indexes and using `isolation: isolate`.
