### ISSUE TITLE
auro-flightline: stopover should have a default value

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/auro-flightline#9]
## Describe the bug
`stopover` doesn't have a default value, so I can't use the boolean attribute shorthand in Svelte, i.e. `<auro-flight-segment stopover>`.

## Expected behavior
`stopover` defaults to false.

**Comment by blackfalcon** [comment]
I am thinking we expand the scope of this issue to revise the API with the new @aurodesignsystem major version release.

**Comment by geoffrich** [comment]
@blackfalcon is it okay to close this with the PR merged into next? Or did you want to wait until the combo issue is closed?
